version: '3'

services:

  # app:
  #   image: aaa
  #   ports:
  #     - 8082:8082

  db: # 自己定義的服務名稱
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
    ports:
      # container port和主機port的配對
      - 3306
    volumes:
      - ./data:/var/lib/mysql
  # volumes:  把你電腦（主機）上的 ./data 資料夾，映射（掛載）到容器（Linux 裡）中的 /var/lib/mysql路徑。

  phpmyadmin: # 自己定義的服務名稱
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: qwe123

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379

  # redis-commander:
  #   image: rediscommander/redis-commander
  #   ports:
  #     - "8091:8081"
  #   environment:
  #     - REDIS_HOSTS=my_redis:redis:6379:0
  #   depends_on:
  #     - redis
